# Generated by Django 5.0.6 on 2024-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('selected_image', models.CharField(choices=[('images/ce_1.jpeg', 'Image 1'), ('images/ce_2.jpeg', 'Image 2'), ('images/ce_3.jpeg', 'Image 3'), ('images/ce_4t.jpeg', 'Image 4'), ('images/ce_5t.jpeg', 'Image 5')], max_length=50)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('text4', models.CharField(max_length=100)),
                ('text5', models.CharField(max_length=100)),
                ('text6', models.CharField(max_length=100)),
                ('text7', models.CharField(max_length=100)),
                ('text8', models.CharField(max_length=100)),
                ('text9', models.CharField(max_length=100)),
                ('text10', models.CharField(max_length=100)),
            ],
        ),
    ]
